### ISSUE TITLE
networking failures aren't always evidence of censorship

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooniprobe-ios#79] opened 2017-02-06 17:43 UTC
The request to `www.hushmail.com` failed with `unknown_failure 1000`. the logs don't yield useful information about what exactly failed there.

The test also flagged dns blocking on `www.bbcworld.com`, which it looks like is due to that not having a valid A record (NXDOMAIN), and my provider filling in a default search page that such requests go to.

**Comment by bassosimone** [comment] 2017-02-06 21:32
> The request to www.hushmail.com failed with unknown_failure 1000. the logs don't yield useful information about what exactly failed there.

I figured it out in measurement-kit/measurement-kit#1121. Thanks for reporting the bug, I also noted it and since we both noticed I realised it was not a transient error and I investigated it.

> The test also flagged dns blocking on www.bbcworld.com, which it looks like is due to that not having a valid A record (NXDOMAIN), and my provider filling in a default search page that such requests go to.

How (and where) do you think we should deal with this? Do you think this is a bug of the way in which `web_connectivity` processes results? Is the same error happening also for `ooni-probe`?

**Comment by hellais** [comment] 2017-02-06 22:33
> The test also flagged dns blocking on www.bbcworld.com, which it looks like is due to that not having a valid A record (NXDOMAIN), and my provider filling in a default search page that such requests go to.

Yes this is also happening in ooniprobe testing and I actually believe that since your provider is returning a valid A record instead of an NXDOMAIN, it in fact a network anomaly and sign that they are spoofing DNS responses.

While I agree that we probably should not be calling this censorship, it is for sure a type of network anomaly that we should be keeping track of.

Maybe something to consider doing to filter out these sorts of anomalies in the future is doing something similar to what Chrome does as in try to resolve a couple of random domains and if we get back a response we take note of this somewhere and use this knowledge to better classify these sorts of anomalies.

I think however that this is actually not a bug with measurement-kit or the ooniprobe software, but rather one of the specification for the web-connectivity test so it should probably be addressed as a ticket in [ooni-spec](https://github.com/TheTorProject/ooni-spec/issues)

**Comment by hellais** [comment] 2017-04-05 17:19
Can we consider this closed since `uknown_error 1000` is now fixed?

**Comment by bassosimone** [comment] 2017-04-19 11:30
> Can we consider this closed since uknown_error 1000 is now fixed?

Yes. I have migrated the suggestion re: detecting systematic spoofing of A records to https://github.com/TheTorProject/ooni-spec/issues/86

**Closed by bassosimone** 2017-04-19 11:30 UTC
